AWSTemplateFormatVersion: 2010-09-09
Description: Updated to view change set implemented
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
  AlertSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        Endpoint: danielhardiman@live.co.uk
        Protocol: email
Outputs:
  BucketName:
    Value: Ref S3Bucket
    Description: Name of the AWS S3 Bucket
