AWSTemplateFormatVersion: 2010-09-09
Resources:
  NestedCall:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://nested-cft-bucket-demo.s3.amazonaws.com/s3BaseCft.yml
      TimeoutInMinutes: 60
Outputs:
  StackRef:
    Value: !Ref NestedCall
  OutputFromNestedStack:
    Value: !GetAtt NestedCall.Outputs.BucketName


