AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Emailaddress:
    Type: String
    Description: 'Enter email for SNS notification'
Resources:
  NestedCall:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters:
        SNSEmail: !Ref Emailaddress
      TemplateURL: https://nested-cft-bucket-demo.s3.amazonaws.com/sns-template-parameter.yml
      TimeoutInMinutes: 60
Outputs:
  StackRef:
    Value: !Ref NestedCall
  
